In [1]:
import pandas as pd
import numpy as np

## Data Import & Data Validation

In [8]:
policy = pd.read_csv("policy_sales_data.csv")

In [9]:
policy

,Customer_ID,Vehicle_ID,Vehicle_Value,Premium,Policy_Purchase_Date,Policy_Start_Date,Policy_End_Date,Policy_Tenure
0,1,1000001,100000,100,1/1/2024,31/12/2024,31/12/2025,1
1,2,1000002,100000,300,1/1/2024,31/12/2024,31/12/2027,3
2,3,1000003,100000,300,1/1/2024,31/12/2024,31/12/2027,3
3,4,1000004,100000,100,1/1/2024,31/12/2024,31/12/2025,1
4,5,1000005,100000,400,1/1/2024,31/12/2024,31/12/2028,4
...,...,...,...,...,...,...,...,...
999907,999908,1999908,100000,200,31/12/2024,31/12/2025,31/12/2027,2
999908,999909,1999909,100000,300,31/12/2024,31/12/2025,31/12/2028,3
999909,999910,1999910,100000,300,31/12/2024,31/12/2025,31/12/2028,3
999910,999911,1999911,100000,300,31/12/2024,31/12/2025,31/12/2028,3
999911,999912,1999912,100000,300,31/12/2024,31/12/2025,31/12/2028,3

In [10]:
policy.head()

,Customer_ID,Vehicle_ID,Vehicle_Value,Premium,Policy_Purchase_Date,Policy_Start_Date,Policy_End_Date,Policy_Tenure
0,1,1000001,100000,100,1/1/2024,31/12/2024,31/12/2025,1
1,2,1000002,100000,300,1/1/2024,31/12/2024,31/12/2027,3
2,3,1000003,100000,300,1/1/2024,31/12/2024,31/12/2027,3
3,4,1000004,100000,100,1/1/2024,31/12/2024,31/12/2025,1
4,5,1000005,100000,400,1/1/2024,31/12/2024,31/12/2028,4

In [11]:
policy.tail()

,Customer_ID,Vehicle_ID,Vehicle_Value,Premium,Policy_Purchase_Date,Policy_Start_Date,Policy_End_Date,Policy_Tenure
999907,999908,1999908,100000,200,31/12/2024,31/12/2025,31/12/2027,2
999908,999909,1999909,100000,300,31/12/2024,31/12/2025,31/12/2028,3
999909,999910,1999910,100000,300,31/12/2024,31/12/2025,31/12/2028,3
999910,999911,1999911,100000,300,31/12/2024,31/12/2025,31/12/2028,3
999911,999912,1999912,100000,300,31/12/2024,31/12/2025,31/12/2028,3

In [12]:
policy.shape

(999912, 8)

In [13]:
policy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999912 entries, 0 to 999911
Data columns (total 8 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Customer_ID           999912 non-null  int64
 1   Vehicle_ID            999912 non-null  int64
 2   Vehicle_Value         999912 non-null  int64
 3   Premium               999912 non-null  int64
 4   Policy_Purchase_Date  999912 non-null  object
 5   Policy_Start_Date     999912 non-null  object
 6   Policy_End_Date       999912 non-null  object
 7   Policy_Tenure         999912 non-null  int64
dtypes: int64(5), object(3)
memory usage: 61.0+ MB

In [16]:
policy.isna().sum()

Customer_ID             0
Vehicle_ID              0
Vehicle_Value           0
Premium                 0
Policy_Purchase_Date    0
Policy_Start_Date       0
Policy_End_Date         0
Policy_Tenure           0
dtype: int64

In [17]:
policy["Policy_Purchase_Date"] = pd.to_datetime(policy["Policy_Purchase_Date"], errors="coerce")

In [18]:
policy["Policy_Start_Date"] = pd.to_datetime(policy["Policy_Start_Date"], errors="coerce")

C:\Users\Tushar Chauhan\AppData\Local\Temp\ipykernel_11252\150314397.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  policy["Policy_Start_Date"] = pd.to_datetime(policy["Policy_Start_Date"], errors="coerce")

In [19]:
policy["Policy_End_Date"] = pd.to_datetime(policy["Policy_End_Date"], errors="coerce")

C:\Users\Tushar Chauhan\AppData\Local\Temp\ipykernel_11252\3271408913.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  policy["Policy_End_Date"] = pd.to_datetime(policy["Policy_End_Date"], errors="coerce")

In [20]:
policy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999912 entries, 0 to 999911
Data columns (total 8 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Customer_ID           999912 non-null  int64
 1   Vehicle_ID            999912 non-null  int64
 2   Vehicle_Value         999912 non-null  int64
 3   Premium               999912 non-null  int64
 4   Policy_Purchase_Date  393408 non-null  datetime64[ns]
 5   Policy_Start_Date     999912 non-null  datetime64[ns]
 6   Policy_End_Date       999912 non-null  datetime64[ns]
 7   Policy_Tenure         999912 non-null  int64
dtypes: datetime64[ns](3), int64(5)
memory usage: 61.0 MB

In [21]:
policy.describe()

,Customer_ID,Vehicle_ID,Vehicle_Value,Premium,Policy_Purchase_Date,Policy_Start_Date,Policy_End_Date,Policy_Tenure
count,999912.000000,9.999120e+05,999912.0,999912.000000,393408,999912,999912,999912.000000
mean,499956.500000,1.499956e+06,100000.0,240.117130,2024-06-21 20:00:00.000000512,2025-07-01 12:00:00,2027-11-25 08:41:48.412739840,2.401171
min,1.000000,1.000001e+06,100000.0,100.000000,2024-01-01 00:00:00,2024-12-31 00:00:00,2025-12-31 00:00:00,1.000000
25%,249978.750000,1.249979e+06,100000.0,200.000000,2024-03-27 00:00:00,2025-04-01 00:00:00,2027-03-02 00:00:00,2.000000
50%,499956.500000,1.499956e+06,100000.0,300.000000,2024-06-21 12:00:00,2025-07-01 12:00:00,2027-12-31 00:00:00,3.000000
75%,749934.250000,1.749934e+06,100000.0,300.000000,2024-09-16 18:00:00,2025-10-01 00:00:00,2028-08-17 00:00:00,3.000000
max,999912.000000,1.999912e+06,100000.0,400.000000,2024-12-12 00:00:00,2025-12-31 00:00:00,2029-12-31 00:00:00,4.000000
std,288649.875522,2.886499e+05,0.0,91.720152,NaN,NaN,NaN,0.917202

In [43]:
policy['Policy_Tenure'].value_counts(normalize=True)*100

Policy_Tenure
3    39.970717
2    29.978038
1    19.985359
4    10.065886
Name: proportion, dtype: float64

In [45]:
policy['Policy_Purchase_Date'].min()
policy['Policy_Purchase_Date'].max()

Timestamp('2024-12-12 00:00:00')

In [22]:
claim = pd.read_csv("claim_data.csv")

In [23]:
claim

       Claim_ID  Customer_ID  Vehicle_ID  Claim_Amount  Claim_Date  Claim_Type
0             1       907392     1907392       10882.3  28/11/2025           1
1             2       102717     1102717       23260.8    6/2/2025           1
2             3       180475     1180475       10330.0    7/3/2025           1
3             4       386343     1386343       20377.8  21/05/2025           1
4             5       470665     1470665       29037.5  21/06/2025           1
...         ...          ...         ...           ...         ...         ...
49401     49402       691348     1691348       10127.4  31/01/2026           1
49402     49403       586954     1586954       29046.0    1/2/2026           1
49403     49404       752724     1752724       20044.2    2/2/2026           1
49404     49405       452009     1452009       25103.4    3/2/2026           1
49405     49406       659395     1659395       27386.7    4/2/2026           1

[49406 rows x 6 columns]

In [24]:
claim.head()

   Claim_ID  Customer_ID  Vehicle_ID  Claim_Amount  Claim_Date  Claim_Type
0         1       907392     1907392       10882.3  28/11/2025           1
1         2       102717     1102717       23260.8    6/2/2025           1
2         3       180475     1180475       10330.0    7/3/2025           1
3         4       386343     1386343       20377.8  21/05/2025           1
4         5       470665     1470665       29037.5  21/06/2025           1

In [25]:
claim.tail()

       Claim_ID  Customer_ID  Vehicle_ID  Claim_Amount  Claim_Date  Claim_Type
49401     49402       691348     1691348       10127.4  31/01/2026           1
49402     49403       586954     1586954       29046.0    1/2/2026           1
49403     49404       752724     1752724       20044.2    2/2/2026           1
49404     49405       452009     1452009       25103.4    3/2/2026           1
49405     49406       659395     1659395       27386.7    4/2/2026           1

In [26]:
claim.shape

(49406, 6)

In [27]:
claim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49406 entries, 0 to 49405
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Claim_ID      49406 non-null  int64
 1   Customer_ID   49406 non-null  int64
 2   Vehicle_ID    49406 non-null  int64
 3   Claim_Amount  49406 non-null  float64
 4   Claim_Date    49406 non-null  object
 5   Claim_Type    49406 non-null  int64
dtypes: float64(1), int64(4), object(1)
memory usage: 2.3+ MB

In [28]:
claim["Claim_Date"] = pd.to_datetime(claim["Claim_Date"], errors = "coerce")

C:\Users\Tushar Chauhan\AppData\Local\Temp\ipykernel_11252\3730822503.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  claim["Claim_Date"] = pd.to_datetime(claim["Claim_Date"], errors = "coerce")

In [30]:
claim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49406 entries, 0 to 49405
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Claim_ID      49406 non-null  int64
 1   Customer_ID   49406 non-null  int64
 2   Vehicle_ID    49406 non-null  int64
 3   Claim_Amount  49406 non-null  float64
 4   Claim_Date    49406 non-null  datetime64[ns]
 5   Claim_Type    49406 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(4)
memory usage: 2.3 MB

In [31]:
claim.describe()

,Claim_ID,Customer_ID,Vehicle_ID,Claim_Amount,Claim_Date,Claim_Type
count,49406.000000,49406.000000,4.940600e+04,49406.000000,49406,49406.000000
mean,24703.500000,500759.914889,1.500760e+06,19999.494748,2025-08-14 12:33:17.101566976,1.006922
min,1.000000,238.000000,1.000238e+06,10000.200000,2025-01-06 00:00:00,1.000000
25%,12352.250000,243810.000000,1.243810e+06,14946.550000,2025-04-28 00:00:00,1.000000
50%,24703.500000,491510.000000,1.491510e+06,19987.850000,2025-08-14 00:00:00,1.000000
75%,37054.750000,742934.500000,1.742934e+06,25025.400000,2025-12-14 00:00:00,1.000000
max,49406.000000,999889.000000,1.999889e+06,29999.500000,2026-02-28 00:00:00,2.000000
std,14262.428037,287947.761506,2.879478e+05,5789.271842,NaN,0.082912

In [32]:
claim.isna().sum()

Claim_ID        0
Customer_ID     0
Vehicle_ID      0
Claim_Amount    0
Claim_Date      0
Claim_Type      0
dtype: int64

In [33]:
policy.keys()

Index(['Customer_ID', 'Vehicle_ID', 'Vehicle_Value', 'Premium',
       'Policy_Purchase_Date', 'Policy_Start_Date', 'Policy_End_Date',
       'Policy_Tenure'],
      dtype='object')

In [34]:
claim.keys()

Index(['Claim_ID', 'Customer_ID', 'Vehicle_ID', 'Claim_Amount', 'Claim_Date',
       'Claim_Type'],
      dtype='object')

In [47]:
from sqlalchemy import create_engine

In [52]:
engine = create_engine("mysql+pymysql://root:153182#Tushar@localhost/insurance_analysis")

In [53]:
policy.to_sql(
    name="policy_sales_data",
    con=engine,
    if_exists="replace",
    index=False
)

999912

In [54]:
claim.to_sql(
    name="claims_data",
    con=engine,
    if_exists="replace",
    index=False
)

49406

#### The datasets were validate in Python using Jupyter Notebook and directly loaded into a MySQL database using SQLAlchemy for further analytical querying.